window.QUIZ_DATA = window.QUIZ_DATA || {};
window.QUIZ_DATA.PASSAGES = {
  // 헨리 / 줄임말(BRT) 지문
  brt: 'You need to know who you are talking to. Henry just sent the following text message to his mother. <br><em>"Mom, I want you to wait just a little longer. BRT."</em><br> Do you think Henry\'s mother correctly understood BRT? Probably not. You can use expressions like BRT (be right there), JK (just kidding), or LOL (laughing out loud) when you text your friends. However, be careful with such expressions when you text your teachers or parents. You need to understand that some of them may not know the meanings of such expressions.',
  // Amy / Nari 전화 지문
  amy: 'Sometimes, you need to pick up the phone. Amy just got the following text message from her best friend Nari. <br><em>"Did you really talk behind my back? I want you to apologize to me."</em><br> Amy wanted to text Nari and explain the situation, but she thought again. "Well, this is too much for a text," she said to herself and called Nari. Texting is okay for casual situations, but sometimes, you need to pick up the phone. This is because misunderstandings can easily happen when you text. Do you need to talk about sensitive issues with your friends? Then, don\'t text them. Call them instead.',
  // 이모지 / Jisu 지문
  emoji: 'You need to understand that people use emojis differently. Yesterday, Jisu gave a birthday gift to her little brother Jihoo. Later, she got the following text message. <br><em>"I loved your gift. Thanks a lot. 😊"</em><br> "Only one smiling face (😊)? I guess he didn\'t like my gift," Jisu thought. When we talk with someone, we use not only words but also facial expressions and body language. In texting, we use emojis instead. Sometimes, a little emoji like 😊 can speak louder than many words. The problem is that not everybody uses emojis in the same way. Some people like to use them a lot, and some don\'t. In addition, the same emojis can mean different things to different people.'
};

window.QUIZ_DATA.CHAPTERS = {

// ───────────────────────────────────────────────────
1:{
  title:"천재(소영순) Lesson 2 (시범)",
  sub:"How Teens Talk Now · 본문 N제 25문항",
  desc:"객관식 22문항 + 서술형 3문항 · 100점",
  info:"📖 BRT 줄임말 · Amy와 Nari · 이모지 지문<br>객관식 22문항 + 서술형 3문항 · 문항당 4점",
  db:"/results_reading_donga_yjm_l2.json",
  q:[
/* 1 */{type:"mc",n:1,t:"RC",p:"독해 · 문맥상 어휘 (A)(B)(C)",
  passage:PASSAGES.brt,
  q:'윗글의 (A), (B), (C) 안에서 문맥에 맞는 낱말로 가장 적절한 것을 고르시오.<br>(A) [correctly / currently] · (B) [careful / cheerful] · (C) [meanings / meetings]',
  c:["① correctly — careful — meanings","② correctly — cheerful — meanings","③ correctly — careful — meetings","④ currently — cheerful — meetings","⑤ currently — careful — meanings"],a:0,
  expl:"(A) \'올바르게\' 이해했는지 묻는 문맥이므로 correctly. (B) 표현에 \'주의해야\' 하므로 careful. (C) 표현의 \'의미\'를 모를 수 있으므로 meanings.",pts:4},
/* 2 */{type:"mc",n:2,t:"RC",p:"독해 · 어휘 쓰임 틀린 개수",
  q:'다음 글의 밑줄 친 (a)~(f) 중, 문맥상 낱말의 쓰임이 적절하지 <strong>않은</strong> 것은 모두 몇 개인가?<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">You can (a)<u>use</u> expressions like BRT, JK, or LOL when you text your (b)<u>parents</u>. However, be (c)<u>careful</u> with such expressions when you text your teachers or parents. You need to (d)<u>understand</u> that some of them may (e)<u>know</u> the (f)<u>meanings</u> of such expressions.</div>',
  c:["① 2개","② 3개","③ 4개","④ 5개","⑤ 6개"],a:0,
  expl:"(b) 줄임말은 parents가 아니라 friends에게 쓴다. (e) 의미를 \'모를 수도\'(may not know) 있다는 내용이어야 한다. 따라서 어색한 것은 2개.",pts:4},
/* 3 */{type:"mc",n:3,t:"RC",p:"독해 · 이어질 행동 추론",
  q:'다음 글의 마지막 문장 직후에 이어질 Nari의 행동으로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">Amy just got the following text message from her best friend Nari. "Did you really talk behind my back? I want you to apologize to me." Amy wanted to text Nari and explain the situation, but she thought again. "Well, this is too much for a text," she said to herself and called Nari.</div>',
  c:["① Amy에게 왜 즉시 문자로 답하지 않았는지 묻는 문자를 보낸다.","② Amy가 보낸 문자 메시지를 무시하고 다른 친구에게 전화를 건다.","③ Amy가 건 전화를 받고 그녀의 설명을 듣기 시작한다.","④ Amy에게 사과할 기회를 주기 위해 그녀의 집으로 찾아간다.","⑤ Amy의 전화에 응답하지 않고 전화를 끊어버린다."],a:2,
  expl:"Amy가 해명하려고 전화를 걸었으므로, Nari가 그 전화를 받고 설명을 듣기 시작하는 것이 가장 자연스럽다.",pts:4},
/* 4 */{type:"mc",n:4,t:"RC",p:"독해 · 지시어 this",
  passage:PASSAGES.amy,
  q:'밑줄 친 <strong>"this"</strong>가 가리키는 것으로 가장 적절한 것을 고르시오. (… "Well, <u>this</u> is too much for a text" …)',
  c:["① Nari asking for an apology without listening","② The long text message Amy planned to write","③ The difficult situation to explain by text","④ The angry feelings Amy had toward Nari","⑤ The hard work of typing a long explanation"],a:2,
  expl:"this는 문자로 설명하기에 곤란하거나 복잡한 \'상황\'을 가리킨다.",pts:4},
/* 5 */{type:"mc",n:5,t:"RC",p:"독해 · 화자 의도",
  q:'다음 대화의 흐름으로 보아, 밑줄 친 질문에 담긴 소년의 의도로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">B: What\'s the biggest country in the world?<br>G: It\'s Russia. I know the smallest country, too. It\'s Vatican City.<br>B: <u>I\'m sorry, but what was the name of the smallest country again?</u><br>G: I said, "Vatican City."</div>',
  c:["① He wants to know if the girl has actually visited the country.","② He doubts that Vatican City is really the smallest country.","③ He missed the name and is asking her to repeat it.","④ He is testing the girl to see if she knows the spelling.","⑤ He disagrees with her answer and wants to argue."],a:2,
  expl:"이름을 놓쳐서 다시 말해달라고 요청하는 의도이다.",pts:4},
/* 6 */{type:"mc",n:6,t:"RC",p:"독해 · 지시어 the situation",
  q:'밑줄 친 (a)the situation이 다음 글에서 의미하는 바로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">Amy just got the following text message from her best friend Nari. "Did you really talk behind my back? I want you to apologize to me." Amy wanted to text Nari and explain (a)<u>the situation</u>, but she thought again. "Well, this is too much for a text," she said to herself and called Nari.</div>',
  c:["① Nari가 Amy에게 사과를 요구하고 있다는 사실","② Amy가 Nari의 험담을 했는지에 대한 오해와 진실","③ Amy가 Nari에게 문자가 아닌 전화를 건 이유","④ 문자 메시지가 사람들 사이에 오해를 일으키는 방식","⑤ Nari가 Amy에게 매우 화가 나 있다는 감정 상태"],a:1,
  expl:"the situation은 Amy가 정말 뒷담화를 했는지, 오해인지에 대한 전후 사정을 의미한다.",pts:4},
/* 7 */{type:"mc",n:7,t:"RC",p:"독해 · 연결사 (A)(B)",
  q:'다음 글의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">You can use expressions like BRT, JK, or LOL when you text your friends. ___(A)___, be careful with such expressions when you text your teachers or parents. You need to understand that ___(B)___ some of them may not know the meanings of such expressions.</div>',
  c:["① However — because","② However — if","③ Therefore — because","④ Therefore — if","⑤ For example — although"],a:0,
  expl:"(A) 대상이 대조되며 전환되므로 However. (B) 주의해야 하는 \'이유\'이므로 because.",pts:4},
/* 8 */{type:"mc",n:8,t:"RC",p:"독해 · 흐름상 어색한 것 (복수정답 ②③)",
  q:'다음 글의 밑줄 친 ⓐ~ⓔ 중, 흐름상 어색한 것을 고르시오. <span style="font-size:12px;color:#6b7280">(원문은 복수정답 ②ⓑ·③ⓒ, 여기서는 ②ⓑ로 채점)</span><br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">Jisu gave a birthday gift to her brother. Later, she ⓐ<u>received</u> the text: "I loved your gift. Thanks a lot. 😊" "Only one smiling face? I guess he ⓑ<u>liked</u> my gift," Jisu ⓒ<u>doubted</u>. When we talk, we use not only words but also ⓓ<u>facial expressions</u> and body language. In texting, we use emojis ⓔ<u>instead</u>.</div>',
  c:["① ⓐ","② ⓑ","③ ⓒ","④ ⓓ","⑤ ⓔ"],a:1,
  expl:"(ⓑ) 이모지 하나뿐인 것을 보고 \'좋아하지 않았다(didn\\'t like)\'고 추측했어야 한다. (ⓒ) 추측 흐름상 doubted가 아니라 thought가 자연스럽다. 원문 복수정답.",pts:4},
/* 9 */{type:"mc",n:9,t:"RC",p:"독해 · 함축 의미",
  q:'밑줄 친 <strong>speak louder than many words</strong>가 문맥상 의미하는 바로 가장 적절한 것을 고르시오.',
  passage:PASSAGES.emoji,
  c:["① Speak with a loud voice.","② Show feelings better than long texts.","③ Cause more confusion than words.","④ Make a loud sound on the phone.","⑤ Show the exact meaning of words."],a:1,
  expl:"작은 이모지 하나가 많은 단어보다 감정을 더 잘 전달할 수 있다는 뜻이다.",pts:4},
/* 10 */{type:"mc",n:10,t:"RC",p:"독해 · 흐름상 적절하지 않은 것",
  q:'다음 글의 밑줄 친 ⓐ~ⓔ 중 흐름상 적절하지 <strong>않은</strong> 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">… we use not only words but also ⓐ<u>facial</u> expressions and body language. In texting, we use emojis ⓑ<u>instead</u>. … can speak ⓒ<u>louder</u> than many words. … not everybody uses emojis in the ⓓ<u>same</u> way. … the same emojis can mean ⓔ<u>identical</u> things to different people.</div>',
  c:["① ⓐ","② ⓑ","③ ⓒ","④ ⓓ","⑤ ⓔ"],a:4,
  expl:"같은 이모지가 사람마다 \'다른(different)\' 것을 의미한다는 내용이어야 하므로 identical은 부적절.",pts:4},
/* 11 */{type:"mc",n:11,t:"RC",p:"독해 · 글의 순서",
  q:'주어진 글 다음에 이어질 글의 순서로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13px;line-height:1.7">Sometimes, you need to pick up the phone. Amy just got the following text message from her best friend Nari.<br>(A) "Well, this is too much for a text," she said and called Nari. …<br>(B) "Did you really talk behind my back? I want you to apologize to me."<br>(C) Amy wanted to text Nari and explain the situation, but she thought again.</div>',
  c:["① (A) - (B) - (C)","② (B) - (A) - (C)","③ (B) - (C) - (A)","④ (C) - (A) - (B)","⑤ (C) - (B) - (A)"],a:2,
  expl:"문자 내용(B) → 설명하려다 망설임(C) → 전화를 거는 결정(A) 순서가 자연스럽다.",pts:4},
/* 12 */{type:"mc",n:12,t:"RC",p:"독해 · 함축 의미",
  q:'밑줄 친 <strong>This is too much for a text</strong>가 의미하는 바로 가장 적절한 것을 고르시오.',
  c:["① The text is too hard to understand.","② It costs too much money to send the text.","③ The problem is too serious to solve by text.","④ Nari is asking for too many things.","⑤ It takes too long to type the message."],a:2,
  expl:"그 문제가 문자로 해결하기엔 너무 무겁거나 심각하다는 의미이다.",pts:4},
/* 13 */{type:"mc",n:13,t:"RC",p:"독해 · 문맥상 어휘 (A)(B)(C)",
  q:'다음 글의 (A), (B), (C) 안에서 문맥에 맞는 낱말로 가장 적절한 것을 고르시오.<br>(A) [language / movement] · (B) [instead / similarly] · (C) [problem / solution]',
  c:["① language — instead — problem","② language — similarly — problem","③ language — instead — solution","④ movement — similarly — solution","⑤ movement — instead — problem"],a:0,
  expl:"(A) 비언어적 의사소통이므로 body language. (B) 표정 대신 이모지를 쓰므로 instead. (C) 같은 방식으로 쓰지 않는 것은 problem.",pts:4},
/* 14 */{type:"mc",n:14,t:"RC",p:"독해 · 글의 순서",
  q:'주어진 글 다음에 이어질 글의 순서로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13px;line-height:1.7">You need to understand that people use emojis differently. Yesterday, Jisu gave a birthday gift to her little brother Jihoo.<br>(A) "Only one smiling face? I guess he didn\'t like my gift," Jisu thought. When we talk … facial expressions and body language.<br>(B) The problem is that not everybody uses emojis in the same way. …<br>(C) Later, she got the following text message. "I loved your gift. Thanks a lot. 😊"<br>(D) In texting, we use emojis instead. … speak louder than many words.</div>',
  c:["① (A) - (C) - (B) - (D)","② (C) - (A) - (D) - (B)","③ (C) - (D) - (A) - (B)","④ (B) - (C) - (A) - (D)","⑤ (A) - (D) - (B) - (C)"],a:1,
  expl:"선물 사건 → 감사 문자 받음(C) → Jisu의 반응(A) → 이모지 역할(D) → 사용이 사람마다 다름(B) 순서.",pts:4},
/* 15 */{type:"mc",n:15,t:"RC",p:"독해 · 추론",
  q:'다음 글을 읽고 추론할 수 있는 내용으로 가장 적절한 것을 고르시오.',
  passage:PASSAGES.brt,
  c:["① Short expressions are useful for everyone, including adults.","② Henry\'s mother understood the text message without any problem.","③ We need to consider the reader when using short expressions.","④ Using \"BRT\" is the most polite way to ask someone to wait.","⑤ Teachers and parents want to learn new slang words from students."],a:2,
  expl:"문자를 보낼 때 읽는 사람을 고려해야 한다는 추론이 가장 적절하다.",pts:4},
/* 16 */{type:"mc",n:16,t:"RC",p:"독해 · 함축 의미 (sensitive issues)",
  q:'다음 글의 밑줄 친 (A)<u>sensitive issues</u>가 의미하는 바로 가장 적절한 것을 고르시오.',
  passage:PASSAGES.amy,
  c:["① Topics that are funny and make everyone laugh.","② Issues that are likely to cause hurt feelings or fights.","③ Information about homework and schedules.","④ Questions about where to eat lunch or dinner.","⑤ News about the latest celebrity gossip."],a:1,
  expl:"오해를 부르거나 감정을 상하게 할 수 있는 민감한 주제를 뜻한다.",pts:4},
/* 17 */{type:"mc",n:17,t:"RC",p:"독해 · 지시어 (a)~(e)",
  q:'밑줄 친 (a)~(e)가 가리키는 것이 <strong>잘못된</strong> 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">W: Did (a)<u>you</u> sign up for the trip?<br>B: Yes. My last name is Juarez.<br>W: Excuse me? But I can\'t find (b)<u>your name</u> on the list. Can (c)<u>you</u> spell (d)<u>it</u> for me?<br>B: Sure. (e)<u>It</u>\'s J-u-a-r-e-z.</div>',
  c:["① (a): 여행을 신청했는지 질문받은 소년","② (b): 소년의 이름(성)","③ (c): 철자를 말해달라고 요청받은 사람","④ (d): 여행 신청자 목록","⑤ (e): \'Juarez\'라는 이름의 철자"],a:3,
  expl:"(d) it은 소년의 이름(성)의 철자를 묻는 것이므로 \'여행 신청자 목록\'이 아니다.",pts:4},
/* 18 */{type:"mc",n:18,t:"RC",p:"독해 · 문맥상 어휘 (A)(B)(C)",
  q:'다음 글의 (A), (B), (C) 안에서 문맥에 맞는 낱말로 가장 적절한 것을 고르시오.<br>(A) [apologize / analyze] · (B) [explain / exclaim] · (C) [casual / causal]',
  c:["① apologize — explain — casual","② apologize — exclaim — casual","③ apologize — explain — causal","④ analyze — exclaim — causal","⑤ analyze — explain — casual"],a:0,
  expl:"(A) \'사과\'하기를 원하므로 apologize. (B) 상황을 \'설명\'하므로 explain. (C) 격식 없는 상황이므로 casual.",pts:4},
/* 19 */{type:"mc",n:19,t:"GR",p:"문법 · 어법상 어색한 것",
  q:'다음 중 어법상 <strong>어색한</strong> 것을 고르시오.',
  c:["① I want you to help me.","② Mom told me to clean my room.","③ My teacher asked us not to be late.","④ He wants his sister stay at home.","⑤ I would like you to join us."],a:3,
  expl:"want는 목적격 보어로 to부정사를 취하므로 stay → to stay로 고쳐야 한다.",pts:4},
/* 20 */{type:"mc",n:20,t:"RC",p:"독해 · 조언 적용",
  q:'다음 글에 나타난 조언을 가장 잘 따르고 있는 사람을 고르시오.',
  passage:PASSAGES.brt,
  c:["① 시간을 절약하려 교장 선생님께 \"Thank you\" 대신 \"THX\"를 보내는 학생","② 할머니께 \"LOL\" 대신 \"Laughing out loud\"라고 완전히 풀어서 문자를 보내는 십 대","③ 어머니에게 모든 최신 속어를 가르치는 아들","④ 오해받는 것이 두려워 부모님께 절대 문자를 보내지 않는 딸","⑤ 친한 친구에게 문자로 비즈니스 영어를 연습하는 친구"],a:1,
  expl:"상대가 이해하도록 줄임말을 풀어서 쓰는 ②가 조언을 가장 잘 따른 행동이다.",pts:4},
/* 21 */{type:"mc",n:21,t:"RC",p:"독해 · 판단 기준 추론",
  q:'다음 글에 나타난 Jisu의 생각("I guess he didn\'t like my gift")을 통해 추론할 수 있는 판단 기준으로 가장 적절한 것을 고르시오.',
  passage:PASSAGES.emoji,
  c:["① 지후가 \"Thanks a lot\"을 진심 없이 사용했다고 의심했다.","② 지후가 원래 감사를 잘 표현하지 않는 성격임을 알았다.","③ 😊 이모티콘이 \'불만\'을 의미하는 부정적 기호라고 해석했다.","④ 이모티콘의 사용 개수가 감정의 강도를 반영한다고 가정했다.","⑤ 지후가 선물보다 다른 것을 더 원했을 것이라고 짐작했다."],a:3,
  expl:"이모티콘이 하나뿐인 것을 보고 좋아하지 않는다고 결론지었으므로, 개수가 감정의 강도를 반영한다고 가정한 것이다.",pts:4},
/* 22 */{type:"mc",n:22,t:"RC",p:"독해 · 빈칸 추론",
  q:'다음 글의 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">… the same emojis can mean different things to different people. Therefore, relying solely on emojis ____________.</div>',
  c:["① guarantees a quick answer from the receiver","② is the best way to show your deep feelings clearly","③ can cause misunderstandings about your real intention","④ helps improve your relationship with people of all ages","⑤ allows you to communicate without language problems"],a:2,
  expl:"이모티콘에만 의존하면 의도와 다른 오해를 부를 수 있다는 내용이 논리적으로 적절하다.",pts:4},
/* 23 (서술형) */{type:"sa",n:23,t:"서술형",p:"서술형 · 화법 전환",
  q:'다음 두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:14px">"He said to me, \'Please close the door.\'"<br>= He <span style="display:inline-block;border-bottom:2px solid var(--blue);min-width:70px">&nbsp;</span> me <span style="display:inline-block;border-bottom:2px solid var(--blue);min-width:50px">&nbsp;</span> close the door.</div>',
  a:"asked to",
  accepts:["asked to","told to"],
  expl:"부탁을 전달하므로 「asked + 목적어 + to부정사」 구조. asked me to close (told도 허용).",pts:4},
/* 24 (서술형은 위치 고르기지만 객관식 보기 형태 → mc 처리) */{type:"mc",n:24,t:"RC",p:"독해 · 문장 위치",
  q:'글의 흐름상 주어진 문장이 들어가기에 가장 적절한 곳을 고르시오.<br><br><div style="background:#fffbe6;border:1px solid #f0e2c0;padding:8px 12px;border-radius:6px;margin-top:8px;font-size:13.5px">Furthermore, an emoji can be understood differently by each person.</div><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13.5px;line-height:1.7">… we use not only words but also facial expressions and body language. ( ① ) In texting, we use emojis instead. ( ② ) Sometimes, a little emoji can speak louder than many words. ( ③ ) The problem is that not everybody uses emojis in the same way. ( ④ ) Some people like to use them a lot, and some don\'t. ( ⑤ )</div>',
  c:["① ①","② ②","③ ③","④ ④","⑤ ⑤"],a:4,
  expl:"빈도 차이를 언급한 뒤(④ 다음), \'게다가\' 해석의 차이를 덧붙이는 ⑤ 위치가 적절하다.",pts:4},
/* 25 (서술형) */{type:"sa",n:25,t:"서술형",p:"서술형 · 우리말 서술 (이유)",
  q:'다음 글을 읽고, 부모님이나 선생님에게 문자를 보낼 때 줄임말을 조심해야 하는 이유를 <strong>우리말로</strong> 쓰시오.<br><br><div style="background:#f8fafb;border:1px solid #e5e7eb;padding:10px 14px;border-radius:6px;margin-top:8px;font-size:13px;line-height:1.7">… be careful with such expressions when you text your teachers or parents. You need to understand that some of them may not know the meanings of such expressions.</div><div style="font-size:12px;color:#6b7280;margin-top:8px">예시 답안: 부모님이나 선생님은 줄임말의 의미를 잘 모를 수 있기 때문이다.</div>',
  a:"부모님이나 선생님은 줄임말의 의미를 잘 모를 수 있기 때문이다",
  accepts:["부모님이나 선생님은 줄임말의 의미를 잘 모를 수 있기 때문이다","부모님이나 선생님이 줄임말의 의미를 모를 수 있기 때문이다","줄임말의 의미를 모를 수 있기 때문","의미를 모를 수 있기 때문","의미를 잘 모를 수 있어서","줄임말의 의미를 모를 수 있어서"],
  expl:"some of them(부모님·선생님)이 such expressions(줄임말)의 의미를 모를 수 있다고 했으므로.",
  sa_text:true, pts:4}
]}

};// end CHAPTERS